import React from 'react';
import { X, ShieldCheck, FileText, CheckCircle } from 'lucide-react';

interface PolicyModalProps {
  isOpen: boolean;
  type: 'terms' | 'privacy' | 'guarantee';
  onClose: () => void;
}

export const PolicyModal: React.FC<PolicyModalProps> = ({ isOpen, type, onClose }) => {
  if (!isOpen) return null;

  const content = {
    guarantee: {
      title: '30-Day Money-Back Guarantee Policy',
      icon: ShieldCheck,
      body: (
        <div className="space-y-4 text-sm text-[#D4CDC5]">
          <p>
            At Mupezeni, our mission is to eliminate risk for Zambian and African retail business owners. We stand behind the quality and operational effectiveness of our AI workforce.
          </p>
          <div className="p-4 rounded-xl bg-[#140C07] border border-[#2D1B0F] space-y-2">
            <h4 className="font-semibold text-white flex items-center gap-2">
              <CheckCircle className="w-4 h-4 text-[#E58330]" />
              How the Guarantee Works
            </h4>
            <p className="text-xs text-[#A8A099]">
              If within the first 30 days of activating your AI Team (AI Customer Support Worker and AI Marketing Worker) you are not completely satisfied with the time saved and sales inquiries handled, simply request a refund via WhatsApp or email.
            </p>
          </div>
          <ul className="list-disc pl-5 space-y-1 text-xs text-[#A8A099]">
            <li>100% full refund of your K2,000 subscription fee.</li>
            <li>No difficult cancellation questions or retention calls.</li>
            <li>Refund processed within 48 hours to your original payment method (Mobile Money or Bank).</li>
            <li>All content created by the AI marketing worker during this period remains yours to keep.</li>
          </ul>
        </div>
      )
    },
    terms: {
      title: 'Terms of Service',
      icon: FileText,
      body: (
        <div className="space-y-4 text-sm text-[#D4CDC5]">
          <p>
            By subscribing to Mupezeni AI retail services, you agree to our standard operating terms.
          </p>
          <div className="space-y-2 text-xs text-[#A8A099]">
            <p><strong>1. Scope of Service:</strong> Mupezeni provides an AI-powered retail workforce consisting of an AI Customer Support Worker, an AI Marketing Worker (~1 post/day, up to 30 posts/month), and an included Business Insights Dashboard.</p>
            <p><strong>2. Pricing & Invoicing:</strong> Fixed rate of K2,000 per month. Billed month-to-month. Zero setup fees. Cancel anytime before your next billing cycle.</p>
            <p><strong>3. Content & Intellectual Property:</strong> All copy, images, and marketing material generated by the AI for your business belong entirely to your company upon payment.</p>
            <p><strong>4. Escalation Responsibility:</strong> The AI Support Worker will handle routine inquiries autonomously. Highly sensitive, dispute, or non-standard queries are escalated directly to the owner.</p>
          </div>
        </div>
      )
    },
    privacy: {
      title: 'Privacy & Data Protection',
      icon: ShieldCheck,
      body: (
        <div className="space-y-4 text-sm text-[#D4CDC5]">
          <p>
            Your customer data, pricing information, and retail inventory details are treated with enterprise confidentiality.
          </p>
          <div className="space-y-2 text-xs text-[#A8A099]">
            <p><strong>1. Data Isolation:</strong> Your store knowledge base, pricing guidelines, and customer inquiries are stored in secure, segregated databases. Your data is never shared with competing stores.</p>
            <p><strong>2. Customer Confidentiality:</strong> Customer phone numbers, addresses, and chat transcripts are strictly used to fulfill inquiries and orders for your business.</p>
            <p><strong>3. Compliance:</strong> We adhere to standard African and international data protection practices and never sell your retail intelligence to third parties.</p>
          </div>
        </div>
      )
    }
  };

  const active = content[type];
  const Icon = active.icon;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-lg rounded-2xl bg-[#0D0805] border border-[#2D1B0F] p-6 shadow-2xl space-y-4">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[#1F140D] pb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-[#E58330]/10 text-[#E58330]">
              <Icon className="w-5 h-5" />
            </div>
            <h3 className="font-bold text-white text-base">{active.title}</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-[#8C827A] hover:text-white hover:bg-white/5 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="max-h-[60vh] overflow-y-auto pr-2 space-y-3">
          {active.body}
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-[#1F140D] flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-[#1C120B] hover:bg-[#2A1B10] text-white text-xs font-semibold border border-[#3A2416] transition-colors"
          >
            Understood & Close
          </button>
        </div>
      </div>
    </div>
  );
};
